timeline
    section Done
        2024-MAR : digital-schedules<br>---------------------------------<br>app released to practice
        2024-MAY : equipment-browser<br>---------------------------------<br>dashboard with product search of all equipment specifed in the practice 
        2024-OCT : post-occupancy-evaluation<br>---------------------------------<br>app for data enty : live dashboard on of POE data on Wiki 
        2025-JAN : room-data-sheets<br>---------------------------------<br>worked with J7516 UoP project team to produce and issue Room Data Sheets from the Revit model
                 : net-zero-metrics<br>---------------------------------<br>Beta release Net Zero Metrics app
    section Doing
        2025-FEB : net-zero-metrics<br>---------------------------------<br>set custom targets. Improve all projects dashboard view
        2025-MAR : digital-schedules<br>---------------------------------<br>search and add equipment between projects
                 : import / export excel
        2025-APR : plantroom-schedule<br>---------------------------------<br>space requirements schedule. add support for A3 landscape view pdf
                 : net-zero-metrics<br>---------------------------------<br>add embodied carbon data
        2025-MAY : room-data-sheets<br>---------------------------------<br>release Revit + Room Data Sheets App 
    section Planned
        2025-XXX : passivhaus-details<br>---------------------------------<br>app to record, dashboard and schedule Passivhaus details
        2025-XXX : document-issue<br>---------------------------------<br>deprecate excel document issue tool and replace with app
                 : add integration with Revit and update the views and sheets tools
        2025-XXX : digital-schedules<br>---------------------------------<br>Revit integration
                 : IFC tools
                 : scheduling assemblies
