mindmap
  root((**Digital 
Transformation**))
    **Automation**
      Efficiency
        More Profit
      Faster Outputs
        Improved Service
    **Real-time Monitoring**
      Easier to manage
    **Building a Growing Resource**
    **Standardisation**
      Data Insights
      Raising Minimum Standards
      Robust Design