[project]
authors = ["jgunstone <j.gunstone@maxfordham.com>"]
channels = ["conda-forge"]
name = "building-code"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
jlab = "jupyter lab"
render = "quarto render ."
preview = "quarto preview ."

[dependencies]
quarto = ">=1.7,<2"
jupyterlab = ">=4.4.0,<5"
