# generated by datamodel-codegen:
#   filename:  AnalyticSession.json
#   timestamp: 2022-02-08T11:30:21+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Extra


class AnalyticSession(BaseModel):
    class Config:
        extra = Extra.forbid

    sessionDate: Optional[datetime] = None
    readingType: Optional[str] = None
    electricUse: Optional[float] = None
    nonElectricUse: Optional[float] = None
    renewableUse: Optional[float] = None
    calculatedEnergyCarbon: Optional[float] = None
    isSelectedSession: Optional[bool] = None
