# generated by datamodel-codegen:
#   filename:  swagger.json
#   timestamp: 2022-02-21T11:23:25+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any
